name: Report

on: [ push ]

jobs:

  setup-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Create envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        API_API_KEY: ${{ secrets.API_API_KEY }}
        API_ORG_ID: ${{ secrets.API_ORG_ID }}
        GOOGLE_MAIL_APPPASSWORD: ${{ secrets.GOOGLE_MAIL_APPPASSWORD }}
        GOOGLE_MAIL_ADDRESS: ${{ secrets.GOOGLE_MAIL_ADDRESS }}
        file_name: .env
        fail_on_empty: false
        sort_keys: false

    - name: Generate requirements.txt
    - uses: actions/checkout@master
    - name: Check requirements.txt
      uses: ekvanox/pipreqs-action@master

      with:
        PROJECT_PATH: .
        REQUIREMENT_PATH: .requirements.txt
        COMMIT_MESSAGE: "Added requirements.txt"

    - name: Install requirements
      uses: actions/setup-python@v5
        - run: pip install -r requirements.txt

    - name: Run Python script
      run: python Report.py
