name: Report

on: [ push ]

jobs:

  run-report:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Create envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        API_API_KEY: ${{ secrets.API_API_KEY }}
        API_ORG_ID: ${{ secrets.API_ORG_ID }}
        GOOGLE_MAIL_APPPASSWORD: ${{ secrets.GOOGLE_MAIL_APPPASSWORD }}
        GOOGLE_MAIL_ADDRESS: ${{ secrets.GOOGLE_MAIL_ADDRESS }}
        file_name: .env
        fail_on_empty: false
        sort_keys: false
        
    - name: Automatic requirements.txt for Python Project
      uses: ryan-rozario/pipreqs-action@master

      # Put an example of mandatory inputs here
      with:
        PROJECT_PATH: .   #default is the root of the repository
        REQUIREMENT_PATH: requirements.txt  #default is requirement.txt in the root of your repository
 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.12'
    
    - name: Run Python script
      run: python Report.py
