name: Create Report

on: [ push ]

jobs:
  get-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check requirements
        uses: ekvanox/pipreqs-action@master

        with:
          PROJECT_PATH: .
          REQUIREMENT_PATH: ./requirements.txt
          COMMIT_MESSAGE: "Updated requirements.txt"

  report:
    runs-on: ubuntu-latest
    needs: get-requirements
    steps:
    - name: 'Create env file'
      run: |
        touch .env
        echo API_API_KEY=${{ secrets.API_API_KEY }} >> .env
        echo API_ORG_ID=${{ secrets.API_ORG_ID }} >> .env
        echo GOOGLE_MAIL_APPPASSWORD: ${{ secrets.GOOGLE_MAIL_APPPASSWORD }} >> .env
        echo GOOGLE_MAIL_ADDRESS: ${{ secrets.GOOGLE_MAIL_ADDRESS }} >> .env
        cat .env

    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r ./requirements.txt

    - name: Run Report
      run: python ./Report.py
      shell: sh

  send-report:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Specify connection via URL (replaces server_address, server_port, secure,
        # username and password)
        #
        # Format:
        #
        #  * smtp://user:password@server:port
        #  * smtp+starttls://user:password@server:port
        connection_url: ${{secrets.GOOGLE_MAIL_CONNECTION}}
        # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
        # Server port, default 25:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{secrets.GOOGLE_MAIL_ADDRESS}}
        # Optional (recommended) mail server password:
        password: ${{secrets.GOOGLE_MAIL_APPPASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: flavio.waser@stud.hslu.ch
        # Required sender full name (address can be skipped):
        from: SACCSF Reporting # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        # html_body: file://README.html
        # Optional carbon copy recipients:
        # cc: kyloren@example.com,leia@example.com
        # Optional blind carbon copy recipients:
        # bcc: r2d2@example.com,hansolo@example.com
        # Optional recipient of the email response:
        reply_to: ${{secrets.GOOGLE_MAIL_ADDRESS}}
        # Optional Message ID this message is replying to:
        in_reply_to: <${{secrets.GOOGLE_MAIL_ADDRESS}}>
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        # attachments: attachments.zip,git.diff,./dist/static/*.js
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: low
        # Optional nodemailerlog: true/false
        nodemailerlog: false
        # Optional nodemailerdebug: true/false if true lognodem will also be set true
        nodemailerdebug: false