name: Create Report

on: [ push ]

jobs:
  get-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check requirements
        uses: ekvanox/pipreqs-action@master

        with:
          PROJECT_PATH: .
          REQUIREMENT_PATH: ./requirements.txt
          COMMIT_MESSAGE: "Updated requirements.txt"

  report:
    runs-on: ubuntu-latest
    needs: get-requirements
    steps:
    - name: 'Create env file'
      run: |
        touch .env
        echo API_API_KEY=${{ secrets.API_API_KEY }} >> .env
        echo API_ORG_ID=${{ secrets.API_ORG_ID }} >> .env
        echo GOOGLE_MAIL_APPPASSWORD: ${{ secrets.GOOGLE_MAIL_APPPASSWORD }} >> .env
        echo GOOGLE_MAIL_ADDRESS: ${{ secrets.GOOGLE_MAIL_ADDRESS }} >> .env
        cat .env

    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r ./requirements.txt

    - name: Run Report
      run: python ./Report.py
      shell: sh

  send-report:
    runs-on: ubuntu-latest
    needs: report
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{SECRETS.GOOGLE_MAIL_ADDRESS}}
          password: ${{SECRETS.GOOGLE_MAIL_APPPASSWORD}}
          subject: SACCSF Report
          to: flavio.waser@stud.hslu.ch
          cc: ce20b112@smail.iitm.ac.in
          from: Swiss-American Chamber of Commerce San Francisco Chapter
          #html_body: file://temp.html
          secure: true
          ignore_cert: true
          convert_markdown: true
          priority: low