name: requirements.yml
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check requirements.txt
        uses: ekvanox/pipreqs-action@master

        with:
          PROJECT_PATH: .
          REQUIREMENT_PATH: requirements.txt
          COMMIT_MESSAGE: "Added requirements.txt"

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt